name: numbers
description: YaruNavigationPage example
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  async: ^2.10.0
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-beta.1
  flutter_localizations:
    sdk: flutter
  handy_window: ^0.3.0
  http: ^0.13.5
  integration_test:
    sdk: flutter
  intl: ^0.18.0
  meta: ^1.8.0
  provider: ^6.0.5
  safe_change_notifier: ^0.2.0
  ubuntu_service: ^0.2.0
  url_launcher: ^6.1.8
  yaru: ^0.9.0
  yaru_icons: ^1.0.2
  yaru_widgets: ^2.3.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
