name: numbers
version: git
summary: Numbers
description: YaruNavigationPage example
confinement: strict
base: core22
grade: stable
license: GPL-3.0+
icon: snap/local/numbers.png
architectures:
  - build-on: amd64
    build-for: amd64
  - build-on: arm64
    build-for: arm64

parts:
  numbers:
    plugin: flutter
    source: .

apps:
  numbers:
    command: numbers
    desktop: data/flutter_assets/assets/numbers.desktop
    extensions: [gnome]
    plugs:
      - network
